vim.cmd.colorscheme "catppuccin-mocha"
--vim.cmd.colorscheme "catppuccin-latte"
--vim.cmd.colorscheme "catppuccin-frappe"
--vim.cmd.colorscheme "catppuccin-macchiato"
--vim.cmd.colorscheme "rose-pine"
--vim.cmd.colorscheme "tokyonight"
--vim.cmd.colorscheme "dracula"
--vim.cmd.colorscheme "moonlight"
