#! /bin/bash

battery_name="battery_CMB1"
percentage="$(upower -i /org/freedesktop/UPower/devices/$battery_name | grep percentage | cut -d ' ' -f15)"
state="$(upower -i /org/freedesktop/UPower/devices/$battery_name | grep state | cut -d ' ' -f20)"
icon=""
declare -i percentage_i=$(echo $percentage | cut -d'%' -f1)

if [ "$state" == "discharging" ] 
then
    if [ "$percentage_i" -gt "0" ] && [ "$percentage_i" -lt "21" ]
    then
        icon=" "
    elif [ "$percentage_i" -gt "20" ] && [ "$percentage_i" -lt "51" ]
    then
        icon=" "
    elif [ "$percentage_i" -gt "50" ] && [ "$percentage_i" -lt "71" ]
    then
        icon=" "
    elif [ "$percentage_i" -gt "70" ] && [ "$percentage_i" -lt "91" ]
    then
        icon=" "
    elif [ "$percentage_i" -gt "0" ]
    then
        icon=" "
    fi
else
    icon=" "
fi

echo "$icon  $percentage"
