#!/bin/bash

volume="$(amixer get Master | sed 6!d | cut -d'[' -f2 | cut -d']' -f1)"
declare -i volume_i=$(echo $volume | cut -d'%' -f1)
not_muted="$(amixer get Master | sed 6!d | cut -d'[' -f3 | cut -d']' -f1)"
icon=""

if [ "$not_muted" == "on" ]
then
    if [ "$volume_i" -gt "0" ] && [ "$volume_i" -lt "15" ]
    then
        icon=" "
    elif [ "$volume_i" -gt "14" ] && [ "$volume_i" -lt "65" ]
    then
        icon=" "
    elif [ "$volume_i" -gt "64" ]
    then
        icon="  "
    fi
else
    icon=" "
fi

echo "$icon $volume"
